version: "3.8"

services:
  shelly-proxy:
    build: .
    container_name: shelly-fems-proxy
    restart: unless-stopped
    network_mode: host           # Ports direkt am Host erreichbar
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      - TZ=Europe/Berlin
